Parameters:
  SlackWebhook:
    Type: String
    Default: ''
  CodeRepoUrl:
    Type: String
    Default: ''
  ComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
  ProjectName:
    Type: String
    Default: ''
Resources:
  CodeBuildIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: !Join ['', [codebuild-, !Ref 'ProjectName', -service-role-policy]]
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Resource:
            - !Join ['', ['arn:aws:logs:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId',
                ':log-group:/aws/codebuild/', !Ref 'ProjectName']]
            - !Join ['', ['arn:aws:logs:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId',
                ':log-group:/aws/codebuild/', !Ref 'ProjectName', ':*']]
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          - Effect: Allow
            Resource:
            - !Join ['', ['arn:aws:s3:::codepipeline-', !Ref 'AWS::Region', -*]]
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:GetObjectVersion
          - Effect: Allow
            Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:GetRepositoryPolicy
            - ecr:DescribeRepositories
            - ecr:ListImages
            - ecr:DescribeImages
            - ecr:BatchGetImage
            - ecr:InitiateLayerUpload
            - ecr:UploadLayerPart
            - ecr:CompleteLayerUpload
            - ecr:PutImage
            Resource: '*'
      Path: /service-role/
      RoleName: !Join ['', [codebuild-, !Ref 'ProjectName', -service-role]]
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref 'ProjectName'
      Source:
        Type: GITHUB
        Location: !Ref 'CodeRepoUrl'
        Auth:
          Type: OAUTH
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/docker:1.12.1
        ComputeType: !Ref 'ComputeType'
        EnvironmentVariables:
        - Name: SLACK_WEBHOOK
          Value: !Ref 'SlackWebhook'
      ServiceRole: !GetAtt [CodeBuildIAMRole, Arn]
